### ISSUE TITLE
php artisan error after Backpack\PermissionManager\PermissionManagerServiceProvider::class is added

### ISSUE THREAD

**Issue by juslintek** [Laravel-Backpack/PermissionManager#74]
I've done everything in here: https://laravel-backpack.readme.io/docs/install-on-laravel-54#section-3-install-backpackcrud till step 9. Now I'm stuck here because of thi error.

When I add Backpack\PermissionManager\PermissionManagerServiceProvider::class
to config/app.php

I get this error during any php artisan command:
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function compileSelect() on null

```

My laravel version is 5.4
php version 7.1
using mongodb as database engine "jenssegers/mongodb"
basically in project homestead setup with mongodb: true in homestead.yaml

Stack Trace of problem:
```
[2017-03-30 12:39:01] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function compileSelect() on null in /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1654
Stack trace:
#0 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1711): Illuminate\Database\Query\Builder->toSql()
#1 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1696): Illuminate\Database\Query\Builder->runSelect()
#2 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(462): Illuminate\Database\Query\Builder->get(Array)
#3 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array)
#4 /home/vagrant/Code/linguobot-admin/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(80): Illuminate\Database\Eloquent\Builder->get()
#5 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(323): Spatie\Permission\PermissionRegistrar->Spatie\Permission\{closure}()
#6 /home/vagrant/Code/linguobot-admin/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(81): Illuminate\Cache\Repository->rememberForever('spatie.permissi...', Object(Closure))
#7 /home/vagrant/Code/linguobot-admin/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(46): Spatie\Permission\PermissionRegistrar->getPermissions()
#8 /home/vagrant/Code/linguobot-admin/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php(31): Spatie\Permission\PermissionRegistrar->registerPermissions()
#9 [internal function]: Spatie\Permission\PermissionServiceProvider->boot(Object(Spatie\Permission\PermissionRegistrar))
#10 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#11 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(762): Illuminate\Container\Container->call(Array)
#15 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->bootProvider(Object(Spatie\Permission\PermissionServiceProvider))
#16 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Spatie\Permission\PermissionServiceProvider), 32)
#17 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): array_walk(Array, Object(Closure))
#18 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#19 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#20 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(270): Illuminate\Foundation\Application->bootstrapWith(Array)
#21 /home/vagrant/Code/linguobot-admin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#22 /home/vagrant/Code/linguobot-admin/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
```

**Comment by tabacitu** [comment]
Hi @juslintek ,

Unfortunately, Backpack doesn't officially support MongoDB. It SHOULD work, because Backpack only uses Eloquent methods, but we can't support it right now because we lack the manpower.

If you manage to fix this, I'd be very happy to hear how you did it. Also, any other things you might discover. It would be great if we document it all, to easily tackle them when we do provide support. If you can and are willing to do any of these, cheers to you man, thanks a lot. I'm sure others that use Backpack + MongoDB in the future will be grateful too. Also we would accept any PRs that fix MongoDB issues.

Sorry I can't be of more help.

Cheers!

**Comment by juslintek** [comment]
@tabacitu Okay I will have a look during free time.
